export const LOAD_DATASOURCE_LIST = 'datasource/LOAD_DATASOURCE_LIST';
export const LOAD_DATASOURCE_LIST_SUCCESS = 'datasource/LOAD_DATASOURCE_LIST_SUCCESS';
export const LOAD_DATASOURCE_LIST_FAIL = 'datasource/LOAD_DATASOURCE_LIST_FAIL';
export const LOAD_DATASOURCE_ADD = 'datasource/LOAD_DATASOURCE_ADD';
export const LOAD_DATASOURCE_ADD_SUCCESS = 'datasource/LOAD_DATASOURCE_ADD_SUCCESS';
export const DELETE_DATASOURCE = 'datasource/DELETE_DATASOURCE';

export const GET_DATASOURCE_TABLES = 'datasource/GET_DATASOURCE_TABLES';
export const GET_DATASOURCE_TABLES_SUCCESS = 'datasource/GET_DATASOURCE_TABLES_SUCCESS';

export const GET_DATASOURCE_TABLES_BY_DS_ID = 'datasource/GET_DATASOURCE_TABLES_BY_DS_ID';
export const GET_DATASOURCE_TABLES_BY_DS_ID_SUCCESS = 'datasource/GET_DATASOURCE_TABLES_BY_DS_ID_SUCCESS';

export const GET_DATASOURCE_TABLE_COLUMNS = 'datasource/GET_DATASOURCE_TABLE_COLUMNS';
export const GET_DATASOURCE_TABLE_COLUMNS_SUCCESS = 'datasource/GET_DATASOURCE_TABLE_COLUMNS_SUCCESS';

export const GET_DATASOURCE_DYNAMIC_TABLE_COLUMNS = 'datasource/GET_DATASOURCE_DYNAMIC_TABLE_COLUMNS';
export const GET_DATASOURCE_DYNAMIC_TABLE_COLUMNS_SUCCESS = 'datasource/GET_DATASOURCE_DYNAMIC_TABLE_COLUMNS_SUCCESS';
